"""Added game_type to Game model

Revision ID: fb9eec51aa37
Revises: 
Create Date: 2025-03-23 16:59:46.406643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9eec51aa37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('additional_notes')
        batch_op.drop_column('game_type')

    # ### end Alembic commands ###
